workflows:
  maui_ios_unsigned:
    name: Build unsigned .NET MAUI IPA for AltStore
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        DOTNET_VERSION: "9.0.304"
    scripts:
      - name: Install .NET SDK (user-local)
        script: |
          curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version $DOTNET_VERSION --install-dir "$HOME/.dotnet"
          export PATH="$HOME/.dotnet:$PATH"
          export DOTNET_ROOT="$HOME/.dotnet"
          dotnet --info
          
      - name: Install MAUI workload (iOS only)
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          export DOTNET_ROOT="$HOME/.dotnet"
          dotnet workload install maui-ios --sdk-version $DOTNET_VERSION
          dotnet workload restore
          dotnet workload list

      - name: Restore NuGet packages (iOS)
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          export DOTNET_ROOT="$HOME/.dotnet"
          dotnet restore MauiApp1.csproj -p:TargetFramework=net9.0-ios

      - name: Build unsigned IPA (iOS)
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          export DOTNET_ROOT="$HOME/.dotnet"
          dotnet publish MauiApp1.csproj \
            -f net9.0-ios \
            -c Release \
            -p:BuildIpa=true \
            -p:EnableCodeSigning=false \
            -p:ArchiveOnBuild=true \
            -p:RuntimeIdentifier=ios-arm64

    artifacts:
      - bin/Release/net9.0-ios/ios-arm64/*.ipa
