workflows:
  maui_ios_unsigned:
    name: Твои покупки
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        DOTNET_VERSION: 9.0.100
        DOTNET_CLI_HOME: /tmp/dotnet
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      xcode: 15.4
    scripts:
      - name: Install .NET SDK
        script: |
          brew install --cask dotnet-sdk
          sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/dotnet
          dotnet --version
      - name: Install MAUI workloads (no sudo)
        script: |
          mkdir -p $DOTNET_CLI_HOME
          dotnet workload install maui --skip-manifest-update
          dotnet workload install ios maccatalyst --skip-manifest-update
      - name: Restore NuGet packages
        script: |
          dotnet restore
      - name: Build iOS project (unsigned)
        script: |
          dotnet publish MauiApp1.csproj \
            -f net9.0-ios \
            -c Release \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:ArchiveOnBuild=true \
            -p:BuildIpa=true \
            -p:Codesign=false
    artifacts:
      - "**/*.ipa"
      - "**/*.app"
